Fixed issue #1902: Compillation failure on AIX
Otherwise, GCC emits the following error:

```
/home/calvin/rpmbuild/BUILD/xdebug-3.0.0/src/lib/timing.h:34:29: error: missing binary operator before token "10"
 if PHP_WIN32 | __APPLE__ | CLOCK_MONOTONIC
                             ^
```

(# omitted because git)